name: Release (Manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v4.1.4)'
        required: true
      title:
        description: 'Release title (optional)'
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release with changelog
        run: |
          npx changelogithub --sanitize ${{ github.event.inputs.tag }} ${{ github.event.inputs.title }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
